### ISSUE TITLE
error en infinity

### ISSUE THREAD

**Issue by Mexalucard0** [Kiri86Dev/kc_admin#1]
sabrás corregir el error del infinity

**Comment by Kiri86-KC** [comment]
> sabrás corregir el error del infinity

Que error?

**Comment by Mexalucard0** [comment]
cuando esta activo el infinity solo ves a las personas que están cerca de ti como si fuera en tu sesión

**Comment by Mexalucard0** [comment]
o algun otro igual con wans

**Comment by MccN90** [comment]
que hay que hacer para abrir el panel pq lo tengo en el server cfg y startea bien pero no abre dentro , tengo permisos de admin puedo hacerlo todo através de comando pero no através del panel pq no se abre

**Comment by Mexalucard0** [comment]
> que hay que hacer para abrir el panel pq lo tengo en el server cfg y startea bien pero no abre dentro , tengo permisos de admin puedo hacerlo todo através de comando pero no através del panel pq no se abre

puede que tengas algo que maneje los mismos comandos y de conflocto, recuerda que en el archivo de configuracion viene para que pongas que puede hacer cada rango. y se apertura con HOME por defecto

**Comment by Kiri86Dev** [comment]
> 

soon new update

**Comment by Kiri86Dev** [comment]
> que hay que hacer para abrir el panel pq lo tengo en el server cfg y startea bien pero no abre dentro , tengo permisos de admin puedo hacerlo todo através de comando pero no através del panel pq no se abre

soon new update

**Comment by Kiri86Dev** [comment]
soon new update
